version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - db-data:/data/db

  spring-app:
    build: .
    ports:
      - '3000:8080'
    depends_on:
      - mongodb


volumes:
  db-data: